# Generated by Django 5.1.7 on 2025-05-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='iimage_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
